export const vehiclesMock = [
  {
    "price": 12999,
    "make": "BMW",
    "model": "1 SERIES",
    "trim": "118d SE 5dr [Nav]",
    "colour": "Alpine white",
    "co2_level": 104,
    "transmission": "Manual",
    "fuel_type": "Diesel",
    "engine_size": 1995,
    "date_first_reg": "28/12/2017",
    "mileage": 11271
  },
  {
    "price": 14699,
    "make": "BMW",
    "model": "1 SERIES",
    "trim": "118d M Sport 5dr [Nav]",
    "colour": "Melbourne red",
    "co2_level": 114,
    "transmission": "Manual",
    "fuel_type": "Diesel",
    "engine_size": 1995,
    "date_first_reg": "04/10/2017",
    "mileage": 13324
  },
  {
    "price": 8999,
    "make": "VAUXHALL",
    "model": "CORSA",
    "trim": "1.4 SRi Vx-line Nav Black 5dr",
    "colour": "Brilliant Summit white",
    "co2_level": 130,
    "transmission": "Manual",
    "fuel_type": "Unleaded",
    "engine_size": 1398,
    "date_first_reg": "09/11/2018",
    "mileage": 7642
  },
  {
    "price": 24999,
    "make": "MITSUBISHI",
    "model": "OUTLANDER",
    "trim": "2.4 PHEV Juro 5dr Auto",
    "colour": "Black",
    "co2_level": 40,
    "transmission": "Automatic",
    "fuel_type": "Unleaded",
    "engine_size": 2360,
    "date_first_reg": "13/06/2019",
    "mileage": 7032
  },
  {
    "price": 7300,
    "make": "NISSAN",
    "model": "JUKE",
    "trim": "1.5 DCI TEKNA 5DR",
    "colour": "Red",
    "transmission": "Manual",
    "fuel_type": "Diesel",
    "engine_size": 1461,
    "date_first_reg": "25/03/2015",
    "mileage": 25029
  },
]